[package]
name = "halo2curves"
version = "0.6.1"
authors = ["Privacy Scaling Explorations team"]
license = "MIT/Apache-2.0"
edition = "2021"
repository = "https://github.com/privacy-scaling-explorations/halo2curves"
readme = "README.md"
description = "Elliptic curve implementations and wrappers for halo2 library"
rust-version = "1.63.0"

[dev-dependencies]
criterion = { version = "0.3", features = ["html_reports"] }
rand_xorshift = "0.3"
ark-std = { version = "0.3" }
bincode = "1.3.3"
serde_json = "1.0.105"
hex = "0.4"
rand_chacha = "0.3.1"
impls = "1"

# Added to make sure we are able to build the lib in the CI.
# Notice this will never be loaded for someone using this lib as dep.
# [target.'cfg(all(target_arch = "wasm32", target_os = "unknown"))'.dev-dependencies]
# getrandom = { version = "0.2", features = ["js"] }

[dependencies]
subtle = "2.5"
ff = { version = "0.13.0", default-features = false, features = ["std"] }
rand = { version = "0.8.3", features = ["small_rng"], default-features = false }
rand_core = { version = "0.6", default-features = false }
group = "0.13.0"
pairing = "0.23.0"
pasta_curves = "0.5.0"
static_assertions = "1.1.0"
lazy_static = "1.4.0"
num-bigint = "0.4.3"
num-traits = "0.2"
paste = "1.0.11"
serde = { version = "1.0", default-features = false, optional = true }
serde_arrays = { version = "0.1.0", optional = true }
hex = { version = "0.4", optional = true, default-features = false, features = ["alloc", "serde"] }
blake2b_simd = "1"
rayon = "1.8"
unroll = "0.1.5"

[features]
default = ["bits"]
asm = []
bits = ["ff/bits"]
bn256-table = []
derive_serde = ["serde/derive", "serde_arrays", "hex", "pasta_curves/serde"]
print-trace = ["ark-std/print-trace"]

[profile.bench]
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false
lto = true
incremental = false
codegen-units = 1

[[bench]]
name = "less_than"
harness = false

[[bench]]
name = "bn256_field"
harness = false

[[bench]]
name = "group"
harness = false

[[bench]]
name = "hash_to_curve"
harness = false

[[bench]]
name = "fft"
harness = false

[[bench]]
name = "msm"
harness = false
